version: "3.4"

services:
  accountico:
    image: fumcloudshop/accountma:latest
    build: .
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://accountico-db:27017/shop
      CALLBACK_URI: http://accountico:6672/accountico/v1/pay/callback
    ports:
      - 6672:6672
    depends_on:
      - accountico-db
    # networks:
    #   maivn:
    #     aliases:
    #       - accountma
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6672/accountico/v1/account/heartbeat"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 1m
    restart: unless-stopped

  authentiq:
    image: sayid/authentiq
    # ports:
    #   - 2000:2000
    depends_on:
      - authentiq-db
    # networks:
    #   maivn:
    #     aliases:
    #       - auth

  authentiq-db:
    image: mongo:4.2.2-bionic
    logging:
      driver: 'none'
    restart: unless-stopped
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: accountma
    #   MONGO_INITDB_ROOT_PASSWORD: accountmanager
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db


  accountico-db:
    image: mvertes/alpine-mongo
    logging:
      driver: 'none'
    restart: unless-stopped
    volumes:
      - db-data-auth:/data/db

# networks:
#   maivn: 

volumes:
  db-data:
  db-data-auth: