version: "2.0"

services:
  accountma:
    image: fumcloudshop/accountma:latest
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 6672:6672
    networks:
      maivn:
        aliases:
          - accountma

    depends_on:
      - db
    restart: unless-stopped

  auth:
    image: sayid/authentiq
    ports:
      - 2000:2000
    networks:
      maivn:
        aliases:
          - auth

  db:
    image: mvertes/alpine-mongo
    logging:
      driver: 'none'
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: accountma
      MONGO_INITDB_ROOT_PASSWORD: accountmanager
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
    networks:
      maivn:
        aliases:
          - db

networks:
  maivn: 
volumes:
  db-data: