version: "3.4"

services:
  accountico:
    image: fumcloudshop/accountma:latest
    build: .
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://accountico-db:27017/shop
      PAYMENT_CALLBACK_URI: http://accountico:6672/accountico/v1/pay/callback
    ports:
      - 6672:6672
    depends_on:
      - accountico-db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6672/accountico/v1/heartbeat"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 1m
    restart: unless-stopped

  authentiq:
    image: sayid/authentiq
    environment:
      AUTHENTIQ_DB_HOST: authentiq-db
      AUTHENTIQ_DB_PORT: 27017
      AUTHENTIQ_DB_NAME: authentiq
      AUTHENTIQ_DB_USERNAME: ''
      AUTHENTIQ_DB_PASSWORD: ''
    # ports:
    #   - 2000:2000
    depends_on:
      - authentiq-db

  authentiq-db:
    image: mvertes/alpine-mongo
    logging:
      driver: 'none'
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ''
      MONGO_INITDB_ROOT_PASSWORD: ''
    # ports:
    #   - "27017:27017"
    volumes:
      - db-data:/data/db


  accountico-db:
    image: mvertes/alpine-mongo
    logging:
      driver: 'none'
    restart: unless-stopped
    volumes:
      - db-data-auth:/data/db

volumes:
  db-data:
  db-data-auth: