version: "2.0"

services:
  accountma:
    image: fumcloudshop/accountma:latest
    build: .
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://accountma:accountmanager@mongo:27017/shop
    ports:
      - 6672:6672
    depends_on:
      - mongo
    # networks:
    #   maivn:
    #     aliases:
    #       - accountma
    restart: unless-stopped

  auth:
    image: sayid/authentiq
    ports:
      - 2000:2000
    depends_on:
      - mongo
    # networks:
    #   maivn:
    #     aliases:
    #       - auth

  mongo:
    image: mongo:4.2.2-bionic
    logging:
      driver: 'none'
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: accountma
      MONGO_INITDB_ROOT_PASSWORD: accountmanager
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db


  db:
    image: mvertes/alpine-mongo
    logging:
      driver: 'none'
    restart: unless-stopped
    volumes:
      - db-data-auth:/data/db

# networks:
#   maivn: 

volumes:
  db-data:
  db-data-auth: